# Generated by Django 4.1.1 on 2023-07-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIL', '0002_remove_bezoekers_message_bezoekers_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimg', models.ImageField(default='UPLOAD', upload_to='media/static')),
            ],
        ),
    ]
