# Generated by Django 4.1.1 on 2023-07-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIL', '0003_qrcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bezoekers',
            name='aanwezigheid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
