# Generated by Django 4.1.1 on 2023-07-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIL', '0004_bezoekers_aanwezigheid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bezoekers',
            name='evenement',
            field=models.CharField(default='MP', max_length=55),
        ),
    ]
