# Generated by Django 4.1.1 on 2023-07-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIL', '0005_bezoekers_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55)),
            ],
        ),
        migrations.DeleteModel(
            name='QRcodes',
        ),
    ]
