# Generated by Django 4.1.1 on 2023-07-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIL', '0006_evenement_delete_qrcodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bezoekers',
            old_name='evenement',
            new_name='evenements',
        ),
    ]
