# Generated by Django 4.1.1 on 2023-07-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIL', '0007_rename_evenement_bezoekers_evenements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bezoekers',
            name='email',
            field=models.CharField(default='MP', max_length=70),
        ),
    ]
