# Generated by Django 4.1.1 on 2023-07-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIL', '0008_alter_bezoekers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='maillijst',
            field=models.FileField(default='r', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evenement',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
