# Generated by Django 4.1.1 on 2023-07-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIL', '0009_evenement_maillijst_alter_evenement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='maillijst',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
