# Generated by Django 4.1.1 on 2023-07-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIL', '0010_alter_evenement_maillijst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bezoekers',
            new_name='Bezoeker',
        ),
    ]
