# Generated by Django 4.1.1 on 2023-07-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIL', '0011_rename_bezoekers_bezoeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='mailtemplate',
            field=models.TextField(default='html templates'),
            preserve_default=False,
        ),
    ]
