# Generated by Django 4.1.1 on 2023-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIL', '0012_evenement_mailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='mailtemplateoutlook',
            field=models.TextField(default='html template'),
            preserve_default=False,
        ),
    ]
