# Generated by Django 4.1.1 on 2023-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIL', '0014_evenement_onderwerpmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='mailtemplate',
            field=models.FileField(upload_to='gmail/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='mailtemplateoutlook',
            field=models.FileField(upload_to='outlook/'),
        ),
    ]
